# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MENU.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from Calcul_d_surfaceZ import Ui_Form6
from Convertir_geo_vers_cart import Ui_Form1
from PD import Ui_Form7
from PI import Ui_Form8
from calculDesLongueurs import Ui_Form5
from calcul_de_M_N_Ralpha import Ui_Form4
from f2 import Ui_Form2
from calculDes3latitudes import Ui_Form3

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        #Form.resize(640, 480)
        Form.setFixedSize(640,475)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(230, -10, 181, 81))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 0);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(30, 90, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"color: rgb(0, 0, 127);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(350, 90, 261, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"color: rgb(0, 0, 127);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(180, 170, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"color: rgb(0, 0, 127);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(30, 250, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"color: rgb(0, 0, 127);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(350, 250, 261, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"color: rgb(0, 0, 127);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(180, 330, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"color: rgb(0, 0, 127);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(Form)
        self.pushButton_7.setGeometry(QtCore.QRect(30, 410, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"color: rgb(0, 0, 127);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(Form)
        self.pushButton_8.setGeometry(QtCore.QRect(350, 410, 261, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"color: rgb(0, 0, 127);")
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 81, 71))
        self.label_2.setStyleSheet("image: url(:/img1/logo_fstt.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(580, 10, 61, 61))
        self.label_3.setStyleSheet("image: url(:/img2/logo-universite-abdelmalek-essaadi-tetouan-uae.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(-170, -130, 921, 701))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("image: url(:/img3/kitty-toft-planets.jpg);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_5.raise_()
        self.label.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()
        self.pushButton_6.raise_()
        self.pushButton_7.raise_()
        self.pushButton_8.raise_()
        self.label_2.raise_()
        self.label_3.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        # ajout click bouton(Convertir geo vers cart)
        self.pushButton_2.clicked.connect(self.pageConvertir2)
        self.pushButton.clicked.connect(self.pageConverti1)
        self.pushButton_3.clicked.connect(self.pageCalcul3)
        self.pushButton_4.clicked.connect(self.pageCalcul4)
        self.pushButton_5.clicked.connect(self.pageCalcul5)
        self.pushButton_6.clicked.connect(self.pageCalcul6)
        self.pushButton_7.clicked.connect(self.PD)
        self.pushButton_8.clicked.connect(self.PI)

    def pageConvertir2 (self):
        # code de page num convetir geo vers cart
        self.Form1 = QtWidgets.QWidget()
        self.ui = Ui_Form1()
        self.ui.setupUi(self.Form1)
        self.Form1.show()
    def pageConverti1(self):
        # code de page num convetir  cart vers geo
        self.Form2 = QtWidgets.QWidget()
        self.ui = Ui_Form2()
        self.ui.setupUi(self.Form2)
        self.Form2.show()
    def pageCalcul3(self):
        # code de page de calcul des 3 latitude
        self.Form3 = QtWidgets.QWidget()
        self.ui = Ui_Form3()
        self.ui.setupUi(self.Form3)
        self.Form3.show()

    def pageCalcul4(self):
        # code de page de calcul des 3 latitude
        self.Form = QtWidgets.QWidget()
        self.ui = Ui_Form4()
        self.ui.setupUi(self.Form)
        self.Form.show()

    def pageCalcul5(self):
        #code de la page de calcul des longueurs
        self.Form = QtWidgets.QWidget()
        self.ui = Ui_Form5()
        self.ui.setupUi(self.Form)
        self.Form.show()

    def pageCalcul6(self):
        #code de la page de calcul de surface d'une partie terrestre
        self.Form = QtWidgets.QWidget()
        self.ui = Ui_Form6()
        self.ui.setupUi(self.Form)
        self.Form.show()

    def PD(self):
        #code de la page de probleme directe
        self.Form = QtWidgets.QWidget()
        self.ui = Ui_Form7()
        self.ui.setupUi(self.Form)
        self.Form.show()


    def PI(self):
        # code de la page de probleme inverse
        self.Form = QtWidgets.QWidget()
        self.ui = Ui_Form8()
        self.ui.setupUi(self.Form)
        self.Form.show()


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "MENU"))
        self.label.setText(_translate("Form", "MENU:"))
        self.pushButton.setText(_translate("Form", "Convertir : (X,Y,Z)→(φ,λ,h)"))
        self.pushButton_2.setText(_translate("Form", "Convertir : (φ,λ,h)→(X,Y,Z)"))
        self.pushButton_3.setText(_translate("Form", "Calcul des 3 latitudes : φ,ψ,β"))
        self.pushButton_4.setText(_translate("Form", "Calcul de : M, N, Rα"))
        self.pushButton_5.setText(_translate("Form", "Calcul des longueurs : S, L"))
        self.pushButton_6.setText(_translate("Form", "Calcul de surface : Z"))
        self.pushButton_7.setText(_translate("Form", "Résoudre PD"))
        self.pushButton_8.setText(_translate("Form", "Résoudre PI"))
import Menu_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
